version: '3.4'

services:
  api:
    build: 
      context: ./API
      dockerfile: Dockerfile
    ports:
      - 9001:80
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bonjing
      POSTGRES_DB: sales_tracker
    ports:
      - 5432:5432
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
  web:
    build: 
      context: ./Sales_Tracker
      dockerfile: Dockerfile
    ports:
      - 4000:4000
volumes:
  my_postgres_data: